<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Bootstrap'                            => __DIR__ . '/Bootstrap.php',
  'SynergyDataGridTest\Module'           => __DIR__ . '/module/Module.php',
  'SynergyDataGridTest\BaseTestClass'    => __DIR__ . '/module/SynergyDataGridTest/BaseTestClass.php',
  'SynergyDataGridTest\Entity\TestBrand' => __DIR__ . '/module/SynergyDataGridTest/Entity/TestBrand.php',
  'SynergyDataGridTest\Entity\TestStore' => __DIR__ . '/module/SynergyDataGridTest/Entity/TestStore.php',
  'SynergyDataGridTest\Entity\TestTree'  => __DIR__ . '/module/SynergyDataGridTest/Entity/TestTree.php',
  'SynergyDataGridTest\Test\CrudTest'    => __DIR__ . '/module/SynergyDataGridTest/Test/CrudTest.php',
  'SynergyDataGridTest\Test\GridTest'    => __DIR__ . '/module/SynergyDataGridTest/Test/GridTest.php',
  'SynergyDataGridTest\TestAdapter'      => __DIR__ . '/module/SynergyDataGridTest/TestAdapter.php',
);
